// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDo1VojBfFy_WhkQHULYGzu5wvltP8ts',
    appId: '1:871431067017:web:774661dd06384d88543d58',
    messagingSenderId: '871431067017',
    projectId: 'expense-app-eb090',
    authDomain: 'expense-app-eb090.firebaseapp.com',
    databaseURL: 'https://expense-app-eb090-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-eb090.appspot.com',
    measurementId: 'G-VW385GMWT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-fh6XyB7324YJFHa7K8TUcV1bm_7-ko',
    appId: '1:871431067017:android:05535c7b2bf03520543d58',
    messagingSenderId: '871431067017',
    projectId: 'expense-app-eb090',
    databaseURL: 'https://expense-app-eb090-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-eb090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pjdiyu2aX0bAa7tEI5JxETV4p4Jumug',
    appId: '1:871431067017:ios:74d2a09a1ffa9e82543d58',
    messagingSenderId: '871431067017',
    projectId: 'expense-app-eb090',
    databaseURL: 'https://expense-app-eb090-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-eb090.appspot.com',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pjdiyu2aX0bAa7tEI5JxETV4p4Jumug',
    appId: '1:871431067017:ios:74d2a09a1ffa9e82543d58',
    messagingSenderId: '871431067017',
    projectId: 'expense-app-eb090',
    databaseURL: 'https://expense-app-eb090-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-eb090.appspot.com',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLDo1VojBfFy_WhkQHULYGzu5wvltP8ts',
    appId: '1:871431067017:web:c4505afc8131d79a543d58',
    messagingSenderId: '871431067017',
    projectId: 'expense-app-eb090',
    authDomain: 'expense-app-eb090.firebaseapp.com',
    databaseURL: 'https://expense-app-eb090-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-app-eb090.appspot.com',
    measurementId: 'G-KM18ZR2B03',
  );
}
